---
title: "PARTIE I. Accompagnement au changement"
author: "équipe KALLM"
date: "2024-11-07"
format: html
---

## Acculturation à l'Intelligence Artificielle

L'Intelligence Artificielle offre une multitude de solutions à diverses besoins des administrations, recensées dans la partie précédente.
Dans un premier temps, il est essentiel de maîtriser *a minima* les outils, techniques et technologies employés pour répondre à ces besoins. Egalement, démystifier l'IA est tout aussi central dans la réussite des projets IA, pour réajuster les attentes des parties prenantes. Dès lors, se pose la question de comment communiquer de manière efficace autour de l'IA ? Cette question prend davantage sens avec des acteurs moins techniques et décisionnaires stratégiques.

### Module d'acculturation de l'IA

Pour communiquer sur l'IA de manière efficace avec des non-initiés, il est nécessaire de  :

* Définir les termes (IA, LLM)
* Définir les concepts et les mécanismes
* Définir ce que les modèles font et ne font pas
* D'avertir sur les hallucinations dans le cas des LLM et d'en évaluer la performance
* D'avertir sur le coût complet d'une solution IA

Pour mieux embarquer les non-initiés, quelques administrations ont mis en place des Lunch-and-Learn autour de l'IA générative, que ce soit sous forme de présentation ou sous forme de quiz.

### Les réseaux autour de l'IA

Pour mieux comprendre l'IA ou faire comprendre auprès des parties prenantes, les réseaux autour de l'IA représentent une opportunité. Par exemple, le réseau du [programme 10%](https://www.10pourcent.etalab.gouv.fr/) et le réseau du [SSPHub](https://ssphub.netlify.app/) mettent en relation des experts autour de la data et de l'IA, permettent d'échanger sur des sujets techniques mais aussi sont ouverts aux non-initiés. Des événements pour un public plus large que les experts sont organisés chaque année comme les [journées 10%](https://10pct.datascience.etalab.studio/les-actualites/le-programme-10-est-de-retour/) ou la [journée du SSPHub](https://ssphub.netlify.app/talk/2024-10-14-network-day/)

## Points d'attentions autour de l'IA générative

Il y a quelques points supplémentaires à bien faire comprendre auprès des parties prenantes quant à l'usage d'IA générative, il s'agit de :

* Démystifier les promesses faites et d'objectiver les performances des solutions d'IA générative
* Bien expliquer son fonctionnement, ce qu'il génère et comment il génère. De mettre en exergue notamment sa nature probabiliste pour formuler une réponse.
* Bien définir le besoin, le modèle utilisé, les raisons de son choix et pourquoi une solution non IA générative n'est pas viable.


